name: "Parse new issue"

on:
  issues:
    types:
      - opened
      # for debugging
      - reopened

jobs:
  updateIssue:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'show') && github.event.sender.login == 'gr2m'
    steps:
      - uses: actions/checkout@v2
      - run: cat $GITHUB_EVENT_PATH
      - uses: stefanbuck/github-issue-praser@main
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/02_show.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}'
