name: "Tweet"
on: 
  workflow_dispatch: 
    inputs:
      text:
        description: 'Text to tweet'     
        required: true
  
jobs:
  tweet: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: node tweet.js
        env:
          TEXT: ${{ github.event.inputs.text }}
          TWITTER_TEST_CONSUMER_KEY: ${{ secrets.TWITTER_TEST_CONSUMER_KEY }}
          TWITTER_TEST_CONSUMER_SECRET: ${{ secrets.TWITTER_TEST_CONSUMER_SECRET }}
          TWITTER_TEST_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_TEST_ACCESS_TOKEN_KEY }}
          TWITTER_TEST_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_TEST_ACCESS_TOKEN_SECRET }}
